
input_folder: 'C:\Users\dmitrii_kalmanovich\source\repos\DataFeedEngine\DataFeedEngineMI2\dbo'
output_folder: 'D:\Code\DatabaseBuild\Instances\DATAFEEDENGINE\Databases'

entities:
  - GICS_GICS
  - Symbol_GVKeyEnhanced
  - Symbol_DandBSymbol
  - KeyDev_FutureEvent
  - KeyDev_FutureEventToObjectToEventType
  - FutureEventMkt_FutureEventMkt
  - FutureEventMkt_FutureEventMktSplitInfo
  - FutureEventMkt_FutureEventMktToObjectToEventType  

src_views_ents:  # for views have to create another set of names due to naming inconsistencies
  - GICS_GICS 
  - Symbol_GVKeyEnhanced
  - Symbol_DandB
  - KeyDev_FutureEvent
  - KeyDev_FutureEventToObjectToEventType
  - KeyDev_FutureEventMkt
  - KeyDev_FutureEventMktSplitInfo
  - KeyDev_FutureEventMktToObjectToEventType

stages:
  #- CLONE_TABLE
  #- CLONE_STG_TABLE
  # - CLONE_VIEW
  # - CREATE_MERGE_SP
  - CREATE_DIRECT_MERGE_SP
  #- CREATE_PULL_SP

code_replacements:
- re_replace_this: \[?(DatafeedEngine\]?|DatafeedEngineCache)\.\[?dbo\]?\.\[?Universe_DailyCompany_tbl\]?
  replace_to: dbo.Universe_Company2_tbl
- re_replace_this: \bCIQDataSnapshot\b
  replace_to: CIQData







