
fail_on_exception: True
use_source_view_clone: True
input_folder: 'C:\Users\dmitrii_kalmanovich\source\repos\DataFeedEngine\DataFeedEngineMI2\dbo'
output_folder: 'D:\Code\DatabaseBuild\Instances\DATAFEEDENGINE\Databases'

entities:
  - IDCSecurity_Security
  - IDCSecurity_TradingItem
  - IDCSecurityToSecurityFeature

src_views_ents:
  - Security_IDCSecurity
  - Security_IDCSecurityTradingItem
  - Security_IDCSecurityToSecurityFeature 

stages:
  #- CLONE_TABLE
  #- CLONE_STG_TABLE
  - CLONE_VIEW
  - CREATE_PULL_SP
  #- CREATE_VIEW_PLACE_HOLDER
  #- CREATE_MERGE_SP
  # - CREATE_DIRECT_MERGE_SP

code_replacements:
- re_replace_this: \b\[?(DatafeedEngine\]?|DatafeedEngineCache)\.\[?dbo\]?\.\[?Universe_DailyCompany\]?\b
  replace_to: dbo.Universe_Company2
- re_replace_this: \bCIQDataSnapshot\b
  replace_to: CIQData







