
input_folder: 'C:\Users\dmitrii_kalmanovich\source\repos\DataFeedEngine\DataFeedEngineMI2\dbo'
output_folder: 'D:\Code\DatabaseBuild\Instances\DATAFEEDENGINE\Databases'

entities:
  - KeyDev_FutureEvent
  - KeyDev_FutureEventToObjectToEventType
  - KeyDev_KeyDev
  - KeyDev_KeyDevToObjectToEventType
  - Professional_PersonProfessionalCompensation
  - Professional_PersonProfessional
  - refdata_CompensationAdjustmentType
  - RefData_CompensationSubType
  - refdata_compensationtype
  - RefData_SubTypeToGIC
  - Symbol_DandB
  - RefData_KeyDevEventType
  - RefData_KeyDevObjectRoleType
  - KeyDev_FutureEventMkt
  - KeyDev_FutureEventMktSplitInfo
  - KeyDev_FutureEventMktToObjectToEventType
  - RefData_AddressType
  - KeyDev_KeyDevPlus
  - KeyDev_KeyDevToObjectToEventType
  - RefData_CharType
  - RefData_CharTypeToSubType
  - Professional_CompensationAdjustment
  - Professional_CompensationDetail


stages:
  #- CLONE_STG_TABLE
  #- CLONE_TABLE
   - CLONE_VIEW

code_replacements:
- re_replace_this: \[?(DatafeedEngine\]?|DatafeedEngineCache)\.\[?dbo\]?\.\[?Universe_DailyCompany_tbl\]?
  replace_to: dbo.Universe_Company2_tbl
- re_replace_this: \bCIQDataSnapshot\b
  replace_to: CIQData







