
fail_on_exception: True
use_source_view_clone: True
input_folder: 'C:\Users\dmitrii_kalmanovich\source\repos\DataFeedEngine\DataFeedEngineMI2\dbo'
output_folder: 'D:\Code\DatabaseBuild\Instances\DATAFEEDENGINE\Databases'

entities:
  - RefData_SecurityType
  - RefData_SecurityGroup
  - RefData_TradingItemStatus
  - RefData_IndexTradingItemType
  - RefData_SecurityFeature
  - RefData_CharType
  - RefData_CharTypeToSubType
  - RefData_IndustryToSIC
  - RefData_SecurityFeature

src_views_ents: []

stages:
  - CLONE_TABLE
  # - CLONE_STG_TABLE
  # - CLONE_VIEW
  #- CREATE_PULL_SP
  #- CREATE_MERGE_SP
  # - CREATE_DIRECT_MERGE_SP

code_replacements:
- re_replace_this: \b\[?(DatafeedEngine\]?|DatafeedEngineCache)\.\[?dbo\]?\.\[?Universe_DailyCompany\]?\b
  replace_to: dbo.Universe_Company2
- re_replace_this: \bCIQDataSnapshot\b
  replace_to: CIQData







