
input_folder: 'C:\Users\dmitrii_kalmanovich\source\repos\DataFeedEngine\DataFeedEngineMI2\dbo'
output_folder: 'D:\Code\DatabaseBuild\Instances\DATAFEEDENGINE\Databases\DataFeedEngineMI'

entities:
  - Professional_CompensationAdjustment
  # - Professional_CompensationDetail


stages:
  #- CLONE_STG_TABLE
  #- CLONE_TABLE
   - CLONE_VIEW

code_replacements:
- re_replace_this: \[?(DatafeedEngine\]?|DatafeedEngineCache)\.\[?dbo\]?\.\[?Universe_DailyCompany_tbl\]?
  replace_to: dbo.Universe_Company2_tbl
- re_replace_this: \bCIQDataSnapshot\.
  replace_to: CIQData.







