
fail_on_exception: False
input_folder: 'C:\Users\dmitrii_kalmanovich\source\repos\DataFeedEngine\DataFeedEngineMI2\dbo'
output_folder: 'D:\Code\DatabaseBuild\Instances\DATAFEEDENGINE\Databases'

entities:
  - RefData_Committee 
  - CompanyRel_CompanyRel
  - Competitors_Competitors
  - Competitors_CompetitorToSource
  - FinAuditor_FinancialToAdvisor
  - BusinessRel_BusinessRel
  - Product_Product
  - KeyDocument_KeyDocument
  - KeyDocument_KeyDocumentToSecurity
  - PeopleBasic_Person
  - PeopleBasic_Professional
  - PeopleBasic_ProToProFunction
  - CompanyNames_AlternateCompanyName
  - CompanyNames_NativeCompanyNameV2
  - CompanyNames_SearchCompanyName


src_views_ents: []
stages:
  - CLONE_TABLE
  #- CLONE_STG_TABLE
  # - CLONE_VIEW
  # - CREATE_MERGE_SP
  # - CREATE_DIRECT_MERGE_SP
  #- CREATE_PULL_SP

code_replacements:
- re_replace_this: \[?(DatafeedEngine\]?|DatafeedEngineCache)\.\[?dbo\]?\.\[?Universe_DailyCompany\]?
  replace_to: dbo.Universe_Company2
- re_replace_this: \bCIQDataSnapshot\b
  replace_to: CIQData







