
input_folder: 'C:\Users\dmitrii_kalmanovich\source\repos\DataFeedEngine\DataFeedEngineMI2\dbo'
output_folder: 'D:\Code\DatabaseBuild\Instances\DATAFEEDENGINE\Databases\DataFeedEngineMI'

entities:
  - GICS_GICS
  - Symbol_GVKeyEnhanced
  - Symbol_DandBSymbol
  - KeyDev_FutureEvent
  - KeyDev_FutureEventToObjectToEventType
  - FutureEventMkt_FutureEventMkt
  - FutureEventMkt_FutureEventMktSplitInfo
  - FutureEventMkt_FutureEventMktToObjectToEventType

src_views_ents:  # for views have to create another set of names due to naming inconsistencies
  - GICS_GICS 
  - Symbol_GVKey 
  - Symbol_GVKeyEnhanced
  - Symbol_DandB
  - KeyDev_FutureEvent
  - KeyDev_FutureEventToObjectToEventType
  - KeyDev_FutureEventMkt
  - KeyDev_FutureEventMktSplitInfo
  - KeyDev_FutureEventMktToObjectToEventType


